<template>
  <div class="stock-flow">
    <reloadAndsearch
      ref="search"
      :config="searchConfig"
      @search="getTableData"
    />
    <TableList
      :pageMethod="getTableData"
      :searchMethod="getTableData"
      :table-data="tableData"
      :tableColumn="tableColumn"
      :query.sync="query"
      :total="total"
      :loading="loadings.table"
      :height="'525px'"
      @select="handleSelectionChange"
    >
      <template v-slot:column-supplierWarehouse="{ row }">
        <div style="padding: 5px 0;">{{ row.supplierWareHouseCode }}&nbsp;{{ row.supplierWareHouse }}</div>
      </template>
      <template #column-ctrl="{ row }">
        {{ `${row.ctrlObj || ''}` }}
      </template>
    </TableList>
  </div>
</template>

<script>
import reloadAndsearch from "@/components/public/reloadAndsearch/reloadAndsearch.vue";
import TableList from "@/components/public/tableList";
export default {
  components: { reloadAndsearch, TableList },
  data() {
    return {
      warehouseList: [],
      skuMcDictPullList: [],

      // 表格数据
      tableData: [],
      total: 0,
      loadings: {
        table: false,
      },
      query: {
        pageNo: 1,
        pageSize: 10,
      },
    };
  },
  computed: {
    searchConfig() {
      const self = this;
      return [
        {
          label: "发生时间",
          tag: "发生时间",
          placeholder: "请选择",
          field: "createdAt",
          value: "",
          type: "date",
          attr: {
            startPlaceholder: "开始日期",
            endPlaceholder: "结束日期",
            "value-format": "yyyy-MM-dd HH:mm:ss",
          },
          datePickerType: "datetimerange",
        },
        {
          label: "供应商仓库",
          placeholder: "请选择供应商仓库",
          field: "warehouse",
          type: "select",
          showCode: true,
          options: this.warehouseList,
          multiple: true,
          option: {
            label: "locationName",
            value: "locationCode",
          },
          callbacks: {
            async remoteMethod(wareHouseName) {
              // const res = await wareHouseExtendList({
              //   wareHouseName,
              //   isSupply: 1, // 1供应商 0非供应商
              //   tenant: '000000',
              // });
              const res = {
                code: 200,
                msg: "success",
                data: {
                  records: [
                    {
                      tenant: "000000",
                      departmentGroupCode: null,
                      parentLocationCode: "",
                      locationCode: "10000",
                      locationName: "广州乐言文创实业有限公司",
                      warehouseType: 1,
                      warehouseStatus: null,
                      entityCode: null,
                    },
                    {
                      tenant: "000000",
                      departmentGroupCode: null,
                      parentLocationCode: "",
                      locationCode: "10001",
                      locationName: "福建集成伞业有限公司",
                      warehouseType: 1,
                      warehouseStatus: null,
                      entityCode: null,
                    },
                    {
                      tenant: "000000",
                      departmentGroupCode: null,
                      parentLocationCode: "",
                      locationCode: "10002",
                      locationName: "浙江新光饰品股份有限公司",
                      warehouseType: 1,
                      warehouseStatus: null,
                      entityCode: null,
                    },
                    {
                      tenant: "000000",
                      departmentGroupCode: null,
                      parentLocationCode: "",
                      locationCode: "10006",
                      locationName: "广州市玛莉安化妆用品有限公司",
                      warehouseType: 1,
                      warehouseStatus: null,
                      entityCode: null,
                    },
                    {
                      tenant: "000000",
                      departmentGroupCode: null,
                      parentLocationCode: "",
                      locationCode: "10010",
                      locationName: "清远市伟诚塑料制品有限公司",
                      warehouseType: 1,
                      warehouseStatus: null,
                      entityCode: null,
                    },
                    {
                      tenant: "000000",
                      departmentGroupCode: null,
                      parentLocationCode: "",
                      locationCode: "10015",
                      locationName: "广东海兴塑胶有限公司",
                      warehouseType: 1,
                      warehouseStatus: null,
                      entityCode: null,
                    },
                    {
                      tenant: "000000",
                      departmentGroupCode: null,
                      parentLocationCode: "",
                      locationCode: "10025",
                      locationName: "东莞市莞美饰品有限公司",
                      warehouseType: 1,
                      warehouseStatus: null,
                      entityCode: null,
                    },
                    {
                      tenant: "000000",
                      departmentGroupCode: null,
                      parentLocationCode: "",
                      locationCode: "10032",
                      locationName: "黄岩坚美塑胶有限公司",
                      warehouseType: 1,
                      warehouseStatus: null,
                      entityCode: null,
                    },
                    {
                      tenant: "000000",
                      departmentGroupCode: null,
                      parentLocationCode: "",
                      locationCode: "10034",
                      locationName: "中山市紫丁香实业有限公司",
                      warehouseType: 1,
                      warehouseStatus: null,
                      entityCode: null,
                    },
                    {
                      tenant: "000000",
                      departmentGroupCode: null,
                      parentLocationCode: "",
                      locationCode: "10071",
                      locationName: "宁波瑞孚工业集团有限公司",
                      warehouseType: 1,
                      warehouseStatus: null,
                      entityCode: null,
                    },
                    {
                      tenant: "000000",
                      departmentGroupCode: null,
                      parentLocationCode: "",
                      locationCode: "10100",
                      locationName: "温州智博印业有限公司",
                      warehouseType: 1,
                      warehouseStatus: null,
                      entityCode: null,
                    },
                    {
                      tenant: "000000",
                      departmentGroupCode: null,
                      parentLocationCode: "",
                      locationCode: "10116",
                      locationName: "珠海市合顺兴日化股份有限公司",
                      warehouseType: 1,
                      warehouseStatus: null,
                      entityCode: null,
                    },
                    {
                      tenant: "000000",
                      departmentGroupCode: null,
                      parentLocationCode: "",
                      locationCode: "10117",
                      locationName: "新丰香知韵工艺品有限公司",
                      warehouseType: 1,
                      warehouseStatus: null,
                      entityCode: null,
                    },
                    {
                      tenant: "000000",
                      departmentGroupCode: null,
                      parentLocationCode: "",
                      locationCode: "10132",
                      locationName: "青岛澳捷尔文化产业有限公司",
                      warehouseType: 1,
                      warehouseStatus: null,
                      entityCode: null,
                    },
                    {
                      tenant: "000000",
                      departmentGroupCode: null,
                      parentLocationCode: "",
                      locationCode: "10165",
                      locationName: "东莞市钟鑫塑料日用品有限公司",
                      warehouseType: 1,
                      warehouseStatus: null,
                      entityCode: null,
                    },
                    {
                      tenant: "000000",
                      departmentGroupCode: null,
                      parentLocationCode: "",
                      locationCode: "10166",
                      locationName: "深圳市三德大康电子有限公司",
                      warehouseType: 1,
                      warehouseStatus: null,
                      entityCode: null,
                    },
                    {
                      tenant: "000000",
                      departmentGroupCode: null,
                      parentLocationCode: "",
                      locationCode: "10176",
                      locationName: "深圳市乐迈科技有限公司",
                      warehouseType: 1,
                      warehouseStatus: null,
                      entityCode: null,
                    },
                    {
                      tenant: "000000",
                      departmentGroupCode: null,
                      parentLocationCode: "",
                      locationCode: "10224",
                      locationName: "宁波卓艺家纺有限公司",
                      warehouseType: 1,
                      warehouseStatus: null,
                      entityCode: null,
                    },
                    {
                      tenant: "000000",
                      departmentGroupCode: null,
                      parentLocationCode: "",
                      locationCode: "10228",
                      locationName: "杭州久积控股有限公司",
                      warehouseType: 1,
                      warehouseStatus: null,
                      entityCode: null,
                    },
                    {
                      tenant: "000000",
                      departmentGroupCode: null,
                      parentLocationCode: "",
                      locationCode: "10268",
                      locationName: "广州末末迪资贸易有限公司",
                      warehouseType: 1,
                      warehouseStatus: null,
                      entityCode: null,
                    },
                  ],
                  total: 104,
                  size: 20,
                  current: 1,
                  pages: 6,
                },
                success: true,
              };
              self.warehouseList = res.data.records;
            },
          },
        },
        {
          label: "业务类型",
          placeholder: "请选择业务类型",
          multiple: true,
          showCode: true,
          options: this.businessTypeList,
          option: {
            label: "dictValue",
            value: "dictCode",
          },
          callbacks: {
            async remoteMethod() {
              // const res = await mcDictExList({
              //   dictTypeCodeList: ['supplierInventoryFlowBusinessType'],
              // });
              const res = {
                code: 200,
                msg: "success",
                data: [
                  {
                    id: 125,
                    tenant: "000000",
                    dictTypeName: "供应商库存流水业务类型",
                    dictTypeCode: "supplierInventoryFlowBusinessType",
                    dictDesc: "供应商库存流水/业务类型",
                    dictType: "2",
                    scopeOfApplication: 1,
                    businessDomain: "",
                    contentType: 1,
                    useCascade: true,
                    status: false,
                    contentResponseList: [
                      {
                        id: 552,
                        dictId: 125,
                        tenant: "000000",
                        dictCode: "1",
                        dictValue: "备料",
                        parentCode: "a",
                        sort: 120,
                        deleted: false,
                      },
                      {
                        id: 553,
                        dictId: 125,
                        tenant: "000000",
                        dictCode: "2",
                        dictValue: "排产",
                        parentCode: "a",
                        sort: 130,
                        deleted: false,
                      },
                      {
                        id: 554,
                        dictId: 125,
                        tenant: "000000",
                        dictCode: "3",
                        dictValue: "成品",
                        parentCode: "a",
                        sort: 140,
                        deleted: false,
                      },
                      {
                        id: 555,
                        dictId: 125,
                        tenant: "000000",
                        dictCode: "4",
                        dictValue: "备发",
                        parentCode: "a",
                        sort: 150,
                        deleted: false,
                      },
                    ],
                  },
                ],
                success: true,
              };
              self.businessTypeList = res.data[0].contentResponseList.filter(
                item => item.parentCode === "a"
              );
            },
          },
          field: "stockPartBizType",
          type: "select",
        },
        {
          label: "SKU",
          placeholder: "请选择SKU",
          multiple: true,
          showCode: true,
          options: this.skuMcDictPullList,
          option: {
            label: "skuName",
            value: "skuCode",
          },
          callbacks: {
            remoteMethod: async skuCodeOrName => {
              // const res = await getSkuListSimple({
              //   skuCodeOrName,
              //   pageNo: 1,
              //   pageSize: 20,
              //   tenant: '000000',
              // });
              const res = {
                code: 200,
                msg: "success",
                data: [
                  {
                    skuCode: "0000000011",
                    skuType: "Z004",
                    barCode: "0000000000017",
                    skuName: "TEST",
                    tinyCategoryCode: "10010101",
                    tinyCategoryName: null,
                    copyrightCode: "",
                    seriesCode: "",
                    bigCategoryCode: "35",
                    bigCategoryName: null,
                    middleCategoryCode: "3500",
                    middleCategoryName: null,
                    smallCategoryCode: "350001",
                    smallCategoryName: null,
                    displayCategoryCode: "",
                    combinePrice: 1000,
                    launchVersionCode: "",
                    status: "2",
                  },
                  {
                    skuCode: "0000000012",
                    skuType: "Z004",
                    barCode: "0000000000024",
                    skuName: "TEST",
                    tinyCategoryCode: "10010101",
                    tinyCategoryName: null,
                    copyrightCode: "",
                    seriesCode: "",
                    bigCategoryCode: "35",
                    bigCategoryName: null,
                    middleCategoryCode: "3500",
                    middleCategoryName: null,
                    smallCategoryCode: "350001",
                    smallCategoryName: null,
                    displayCategoryCode: "",
                    combinePrice: 1000,
                    launchVersionCode: "",
                    status: "2",
                  },
                  {
                    skuCode: "0000000013",
                    skuType: "Z004",
                    barCode: "0000000000130",
                    skuName: "TEST",
                    tinyCategoryCode: "10010101",
                    tinyCategoryName: null,
                    copyrightCode: "",
                    seriesCode: "",
                    bigCategoryCode: "35",
                    bigCategoryName: null,
                    middleCategoryCode: "3500",
                    middleCategoryName: null,
                    smallCategoryCode: "350001",
                    smallCategoryName: null,
                    displayCategoryCode: "",
                    combinePrice: 1500,
                    launchVersionCode: "",
                    status: "2",
                  },
                  {
                    skuCode: "0000000014",
                    skuType: "Z004",
                    barCode: "0000000000147",
                    skuName: "TEST",
                    tinyCategoryCode: "10010101",
                    tinyCategoryName: null,
                    copyrightCode: "",
                    seriesCode: "",
                    bigCategoryCode: "35",
                    bigCategoryName: null,
                    middleCategoryCode: "3500",
                    middleCategoryName: null,
                    smallCategoryCode: "350001",
                    smallCategoryName: null,
                    displayCategoryCode: "",
                    combinePrice: 2000,
                    launchVersionCode: "",
                    status: "2",
                  },
                  {
                    skuCode: "0000000018",
                    skuType: "Z004",
                    barCode: "0000000000185",
                    skuName: "TEST",
                    tinyCategoryCode: "10010101",
                    tinyCategoryName: null,
                    copyrightCode: "",
                    seriesCode: "",
                    bigCategoryCode: "35",
                    bigCategoryName: null,
                    middleCategoryCode: "3500",
                    middleCategoryName: null,
                    smallCategoryCode: "350001",
                    smallCategoryName: null,
                    displayCategoryCode: "",
                    combinePrice: 3900,
                    launchVersionCode: "",
                    status: "2",
                  },
                  {
                    skuCode: "0000000020",
                    skuType: "Z004",
                    barCode: "0000000000208",
                    skuName: "TEST",
                    tinyCategoryCode: "10010101",
                    tinyCategoryName: null,
                    copyrightCode: "",
                    seriesCode: "",
                    bigCategoryCode: "35",
                    bigCategoryName: null,
                    middleCategoryCode: "3500",
                    middleCategoryName: null,
                    smallCategoryCode: "350001",
                    smallCategoryName: null,
                    displayCategoryCode: "",
                    combinePrice: 4900,
                    launchVersionCode: "",
                    status: "2",
                  },
                  {
                    skuCode: "0100000011",
                    skuType: "Z001",
                    barCode: "4500901000117/4502337000112/4506597000110",
                    skuName: "TEST",
                    tinyCategoryCode: "10030102",
                    tinyCategoryName: null,
                    copyrightCode: "",
                    seriesCode: "",
                    bigCategoryCode: "29",
                    bigCategoryName: null,
                    middleCategoryCode: "2901",
                    middleCategoryName: null,
                    smallCategoryCode: "290130",
                    smallCategoryName: null,
                    displayCategoryCode: "2219",
                    combinePrice: 1000,
                    launchVersionCode: "",
                    status: "2",
                  },
                  {
                    skuCode: "0100000021",
                    skuType: "Z001",
                    barCode: "4500901000216",
                    skuName: "TEST",
                    tinyCategoryCode: "10030102",
                    tinyCategoryName: null,
                    copyrightCode: "",
                    seriesCode: "",
                    bigCategoryCode: "29",
                    bigCategoryName: null,
                    middleCategoryCode: "2901",
                    middleCategoryName: null,
                    smallCategoryCode: "290130",
                    smallCategoryName: null,
                    displayCategoryCode: "2219",
                    combinePrice: 1000,
                    launchVersionCode: "",
                    status: "2",
                  },
                  {
                    skuCode: "0100000031",
                    skuType: "Z001",
                    barCode: "4500901000315/4502337000310/4506597000318",
                    skuName: "TEST",
                    tinyCategoryCode: "10030102",
                    tinyCategoryName: null,
                    copyrightCode: "",
                    seriesCode: "",
                    bigCategoryCode: "29",
                    bigCategoryName: null,
                    middleCategoryCode: "2901",
                    middleCategoryName: null,
                    smallCategoryCode: "290130",
                    smallCategoryName: null,
                    displayCategoryCode: "2219",
                    combinePrice: 1000,
                    launchVersionCode: "",
                    status: "2",
                  },
                  {
                    skuCode: "0100000041",
                    skuType: "Z001",
                    barCode: "4500901000414",
                    skuName: "TEST",
                    tinyCategoryCode: "10030102",
                    tinyCategoryName: null,
                    copyrightCode: "",
                    seriesCode: "",
                    bigCategoryCode: "29",
                    bigCategoryName: null,
                    middleCategoryCode: "2901",
                    middleCategoryName: null,
                    smallCategoryCode: "290130",
                    smallCategoryName: null,
                    displayCategoryCode: "2219",
                    combinePrice: 1000,
                    launchVersionCode: "",
                    status: "2",
                  },
                  {
                    skuCode: "0100000051",
                    skuType: "Z001",
                    barCode: "4500901000513",
                    skuName: "TEST",
                    tinyCategoryCode: "10030102",
                    tinyCategoryName: null,
                    copyrightCode: "",
                    seriesCode: "",
                    bigCategoryCode: "29",
                    bigCategoryName: null,
                    middleCategoryCode: "2901",
                    middleCategoryName: null,
                    smallCategoryCode: "290130",
                    smallCategoryName: null,
                    displayCategoryCode: "2219",
                    combinePrice: 1000,
                    launchVersionCode: "",
                    status: "2",
                  },
                  {
                    skuCode: "0100000061",
                    skuType: "Z001",
                    barCode: "4501901000619",
                    skuName: "TEST",
                    tinyCategoryCode: "10010102",
                    tinyCategoryName: null,
                    copyrightCode: "",
                    seriesCode: "",
                    bigCategoryCode: "20",
                    bigCategoryName: null,
                    middleCategoryCode: "2001",
                    middleCategoryName: null,
                    smallCategoryCode: "200152",
                    smallCategoryName: null,
                    displayCategoryCode: "2170",
                    combinePrice: 1000,
                    launchVersionCode: "",
                    status: "2",
                  },
                  {
                    skuCode: "0100000071",
                    skuType: "Z001",
                    barCode: "4501901000718",
                    skuName: "TEST",
                    tinyCategoryCode: "10010102",
                    tinyCategoryName: null,
                    copyrightCode: "",
                    seriesCode: "",
                    bigCategoryCode: "20",
                    bigCategoryName: null,
                    middleCategoryCode: "2001",
                    middleCategoryName: null,
                    smallCategoryCode: "200152",
                    smallCategoryName: null,
                    displayCategoryCode: "2170",
                    combinePrice: 1000,
                    launchVersionCode: "",
                    status: "2",
                  },
                  {
                    skuCode: "0100000081",
                    skuType: "Z001",
                    barCode: "4501901000817",
                    skuName: "TEST",
                    tinyCategoryCode: "10010102",
                    tinyCategoryName: null,
                    copyrightCode: "",
                    seriesCode: "",
                    bigCategoryCode: "20",
                    bigCategoryName: null,
                    middleCategoryCode: "2001",
                    middleCategoryName: null,
                    smallCategoryCode: "200152",
                    smallCategoryName: null,
                    displayCategoryCode: "2170",
                    combinePrice: 1000,
                    launchVersionCode: "",
                    status: "2",
                  },
                  {
                    skuCode: "0100000091",
                    skuType: "Z001",
                    barCode: "4501901000916",
                    skuName: "TEST",
                    tinyCategoryCode: "10010102",
                    tinyCategoryName: null,
                    copyrightCode: "",
                    seriesCode: "",
                    bigCategoryCode: "20",
                    bigCategoryName: null,
                    middleCategoryCode: "2001",
                    middleCategoryName: null,
                    smallCategoryCode: "200152",
                    smallCategoryName: null,
                    displayCategoryCode: "2170",
                    combinePrice: 1000,
                    launchVersionCode: "",
                    status: "2",
                  },
                  {
                    skuCode: "0100000101",
                    skuType: "Z001",
                    barCode: "4501901001012",
                    skuName: "TEST",
                    tinyCategoryCode: "10010102",
                    tinyCategoryName: null,
                    copyrightCode: "",
                    seriesCode: "",
                    bigCategoryCode: "20",
                    bigCategoryName: null,
                    middleCategoryCode: "2001",
                    middleCategoryName: null,
                    smallCategoryCode: "200152",
                    smallCategoryName: null,
                    displayCategoryCode: "2170",
                    combinePrice: 1000,
                    launchVersionCode: "",
                    status: "2",
                  },
                  {
                    skuCode: "0100000111",
                    skuType: "Z001",
                    barCode: "4501901001111",
                    skuName: "TEST",
                    tinyCategoryCode: "10010102",
                    tinyCategoryName: null,
                    copyrightCode: "",
                    seriesCode: "",
                    bigCategoryCode: "20",
                    bigCategoryName: null,
                    middleCategoryCode: "2001",
                    middleCategoryName: null,
                    smallCategoryCode: "200152",
                    smallCategoryName: null,
                    displayCategoryCode: "2170",
                    combinePrice: 1000,
                    launchVersionCode: "",
                    status: "2",
                  },
                  {
                    skuCode: "0100000121",
                    skuType: "Z001",
                    barCode: "4501901001210",
                    skuName: "TEST",
                    tinyCategoryCode: "10010102",
                    tinyCategoryName: null,
                    copyrightCode: "",
                    seriesCode: "",
                    bigCategoryCode: "20",
                    bigCategoryName: null,
                    middleCategoryCode: "2001",
                    middleCategoryName: null,
                    smallCategoryCode: "200152",
                    smallCategoryName: null,
                    displayCategoryCode: "2170",
                    combinePrice: 1000,
                    launchVersionCode: "",
                    status: "2",
                  },
                  {
                    skuCode: "0100000131",
                    skuType: "Z001",
                    barCode: "4501901001319",
                    skuName: "TEST",
                    tinyCategoryCode: "10010102",
                    tinyCategoryName: null,
                    copyrightCode: "",
                    seriesCode: "",
                    bigCategoryCode: "20",
                    bigCategoryName: null,
                    middleCategoryCode: "2001",
                    middleCategoryName: null,
                    smallCategoryCode: "200152",
                    smallCategoryName: null,
                    displayCategoryCode: "2170",
                    combinePrice: 1000,
                    launchVersionCode: "",
                    status: "2",
                  },
                  {
                    skuCode: "0100000141",
                    skuType: "Z001",
                    barCode: "4501901001418",
                    skuName: "TEST",
                    tinyCategoryCode: "10010102",
                    tinyCategoryName: null,
                    copyrightCode: "",
                    seriesCode: "",
                    bigCategoryCode: "20",
                    bigCategoryName: null,
                    middleCategoryCode: "2001",
                    middleCategoryName: null,
                    smallCategoryCode: "200152",
                    smallCategoryName: null,
                    displayCategoryCode: "2170",
                    combinePrice: 1000,
                    launchVersionCode: "",
                    status: "2",
                  },
                ],
                success: true,
              };
              this.skuMcDictPullList = res.data || [];
            },
          },
          field: "skuCodeList",
          value: "",
          type: "select",
        },
        {
          label: "来源业务活动",
          placeholder: "请选择来源业务活动",
          multiple: true,
          showCode: true,
          options: this.sourceBizList,
          option: {
            label: "dictValue",
            value: "dictCode",
          },
          callbacks: {
            async remoteMethod() {
              // const res = await mcDictExList({
              //   dictTypeCodeList: ['warehouseInventoryLogSourceBiz'],
              // });
              const res = {
                code: 200,
                msg: "success",
                data: [
                  {
                    id: 132,
                    tenant: "000000",
                    dictTypeName: "仓库库存流水来源业务活动",
                    dictTypeCode: "warehouseInventoryLogSourceBiz",
                    dictDesc: "仓库库存流水/来源业务活动",
                    dictType: "2",
                    scopeOfApplication: 1,
                    businessDomain: "",
                    contentType: 1,
                    useCascade: false,
                    status: false,
                    contentResponseList: [
                      {
                        id: 597,
                        dictId: 132,
                        tenant: "000000",
                        dictCode: "1",
                        dictValue: "建议单处理",
                        parentCode: "",
                        sort: 100,
                        deleted: false,
                      },
                      {
                        id: 598,
                        dictId: 132,
                        tenant: "000000",
                        dictCode: "2",
                        dictValue: "计划单推送",
                        parentCode: "",
                        sort: 110,
                        deleted: false,
                      },
                      {
                        id: 599,
                        dictId: 132,
                        tenant: "000000",
                        dictCode: "3",
                        dictValue: "计划单取消",
                        parentCode: "",
                        sort: 120,
                        deleted: false,
                      },
                      {
                        id: 600,
                        dictId: 132,
                        tenant: "000000",
                        dictCode: "4",
                        dictValue: "库存检查",
                        parentCode: "",
                        sort: 130,
                        deleted: false,
                      },
                      {
                        id: 6536,
                        dictId: 132,
                        tenant: "000000",
                        dictCode: "28",
                        dictValue: "通知备料",
                        parentCode: "",
                        sort: 140,
                        deleted: false,
                      },
                      {
                        id: 6537,
                        dictId: 132,
                        tenant: "000000",
                        dictCode: "29",
                        dictValue: "取消备料",
                        parentCode: "",
                        sort: 150,
                        deleted: false,
                      },
                      {
                        id: 6538,
                        dictId: 132,
                        tenant: "000000",
                        dictCode: "30",
                        dictValue: "在单抵扣",
                        parentCode: "",
                        sort: 160,
                        deleted: false,
                      },
                    ],
                  },
                ],
                success: true,
              };
              self.sourceBizList = res.data[0].contentResponseList;
            },
          },
          field: "bizActivity",
          type: "select",
        },
        {
          label: "来源业务单号",
          field: "sourceBizOrderNo",
          type: "input",
        },
        {
          label: "日期",
          tag: "日期",
          field: "stockDate",
          type: "date",
          attr: {
            startPlaceholder: "开始日期",
            endPlaceholder: "结束日期",
            "value-format": "yyyy-MM-dd HH:mm:ss",
          },
          datePickerType: "daterange",
        },
        {
          label: "调整方式",
          placeholder: "请选择调整方式",
          multiple: true,
          showCode: true,
          options: this.ctrlWayList,
          option: {
            label: "dictValue",
            value: "dictCode",
          },
          callbacks: {
            async remoteMethod() {
              // const res = await mcDictExList({
              //   dictTypeCodeList: ['inventoryLogCtrlLog'],
              // });
              const res = {
                code: 200,
                msg: "success",
                data: [
                  {
                    id: 131,
                    tenant: "000000",
                    dictTypeName: "库存流水调整方式",
                    dictTypeCode: "inventoryLogCtrlLog",
                    dictDesc:
                      "供应商库存流水/在单库存流水/仓库库存流水 -> 调整方式",
                    dictType: "2",
                    scopeOfApplication: 1,
                    businessDomain: "",
                    contentType: 1,
                    useCascade: false,
                    status: false,
                    contentResponseList: [
                      {
                        id: 594,
                        dictId: 131,
                        tenant: "000000",
                        dictCode: "1",
                        dictValue: "增加",
                        parentCode: "",
                        sort: 100,
                        deleted: false,
                      },
                      {
                        id: 595,
                        dictId: 131,
                        tenant: "000000",
                        dictCode: "2",
                        dictValue: "扣减",
                        parentCode: "",
                        sort: 110,
                        deleted: false,
                      },
                      {
                        id: 596,
                        dictId: 131,
                        tenant: "000000",
                        dictCode: "3",
                        dictValue: "覆盖",
                        parentCode: "",
                        sort: 120,
                        deleted: false,
                      },
                    ],
                  },
                ],
                success: true,
              };
              self.ctrlWayList = res.data[0].contentResponseList;
            },
          },
          span: 6,
          field: "ctrlWay",
          type: "select",
        },
      ];
    },
    tableColumn() {
      return [
        { label: '操作', type:"selection", width: 45, align: "center"},
        { label: "发生时间", prop: "createTime", width: 200 },
        { label: "供应商仓库", slots: { name: "column-supplierWarehouse" } },
        { label: "业务类型", prop: "stockPartName", width: 100},
        { label: "SKU编码", prop: "sku", width: 150},
        { label: "SKU名称", prop: "skuName"},
        { label: "日期", prop: "stockDate", width: 200 },
        { label: "来源业务活动", prop: "sourceBiz", width: 150},
        { label: "来源业务单据号", prop: "sourceBizOrderNo", width: 200},
        { label: "调整方式", slots: { name: "column-ctrl" }, width: 150}
      ];
    },
    statusClass() {
      return {
        1: {
          class: "blue",
        },
        2: {
          class: "grey",
        },
      };
    },
  },
  methods: {
    getTableData() {
      const res = {
          data: {
            records: [
              {
                createTime: '2022-11-29 11:47:44',
                supplierWareHouseCode: '10000',
                supplierWareHouse: '广州乐言文创实业有限公司',
                stockPartCode: 'PRO001',
                stockPartName: '成品',
                sku: '2009015011108',
                skuName: 'TEST',
                ctrlWay: 1,
                ctrlNum: 5,
                ctrlObj: '总数增加',
                sourceBiz: '供应商手动维护',
                sourceBizOrderNo: null,
                stockDate: null,
              },
              {
                createTime: '2022-11-29 11:47:44',
                supplierWareHouseCode: '10000',
                supplierWareHouse: '广州乐言文创实业有限公司',
                stockPartCode: 'PRO001',
                stockPartName: '成品',
                sku: '2009015011108',
                skuName: 'TEST',
                ctrlWay: 1,
                ctrlNum: 5,
                ctrlObj: '可用增加',
                sourceBiz: '供应商手动维护',
                sourceBizOrderNo: null,
                stockDate: null,
              },
              {
                createTime: '2022-11-29 11:47:44',
                supplierWareHouseCode: '10000',
                supplierWareHouse: '广州乐言文创实业有限公司',
                stockPartCode: 'FAC001',
                stockPartName: '排产',
                sku: '2009015011108',
                skuName: 'TEST',
                ctrlWay: 2,
                ctrlNum: 5,
                ctrlObj: '总数减少',
                sourceBiz: '供应商手动维护',
                sourceBizOrderNo: null,
                stockDate: null,
              },
              {
                createTime: '2022-11-29 10:22:12',
                supplierWareHouseCode: '10000',
                supplierWareHouse: '广州乐言文创实业有限公司',
                stockPartCode: 'FAC001',
                stockPartName: '排产',
                sku: '2009015012105',
                skuName: 'TEST',
                ctrlWay: 3,
                ctrlNum: 10,
                ctrlObj: '总数覆盖',
                sourceBiz: '供应商手动维护',
                sourceBizOrderNo: null,
                stockDate: null,
              },
              {
                createTime: '2022-11-29 10:22:12',
                supplierWareHouseCode: '10000',
                supplierWareHouse: '广州乐言文创实业有限公司',
                stockPartCode: 'PRE001',
                stockPartName: '备料',
                sku: '2009015012105',
                skuName: 'TEST',
                ctrlWay: 2,
                ctrlNum: 1,
                ctrlObj: '总数减少',
                sourceBiz: '供应商手动维护',
                sourceBizOrderNo: null,
                stockDate: null,
              },
              {
                createTime: '2022-11-29 10:22:12',
                supplierWareHouseCode: '10000',
                supplierWareHouse: '广州乐言文创实业有限公司',
                stockPartCode: 'PRE001',
                stockPartName: '备料',
                sku: 'SKU2211000036',
                skuName: '哈哈哈通用',
                ctrlWay: 2,
                ctrlNum: 9,
                ctrlObj: '总数减少',
                sourceBiz: '供应商手动维护',
                sourceBizOrderNo: null,
                stockDate: null,
              },
              {
                createTime: '2022-11-29 10:22:12',
                supplierWareHouseCode: '10000',
                supplierWareHouse: '广州乐言文创实业有限公司',
                stockPartCode: '',
                stockPartName: '',
                sku: '2009015012105',
                skuName: 'TEST',
                ctrlWay: 1,
                ctrlNum: 9,
                ctrlObj: '占用增加',
                sourceBiz: '供应商手动维护',
                sourceBizOrderNo: null,
                stockDate: null,
              },
              {
                createTime: '2022-11-29 10:19:21',
                supplierWareHouseCode: '10000',
                supplierWareHouse: '广州乐言文创实业有限公司',
                stockPartCode: '',
                stockPartName: '',
                sku: 'SKU2211000036',
                skuName: '哈哈哈通用',
                ctrlWay: 1,
                ctrlNum: 100,
                ctrlObj: '占用增加',
                sourceBiz: '供应商手动维护',
                sourceBizOrderNo: null,
                stockDate: null,
              },
              {
                createTime: '2022-11-29 10:19:21',
                supplierWareHouseCode: '10000',
                supplierWareHouse: '广州乐言文创实业有限公司',
                stockPartCode: 'PRE001',
                stockPartName: '备料',
                sku: 'SKU2211000036',
                skuName: '哈哈哈通用',
                ctrlWay: 1,
                ctrlNum: 100,
                ctrlObj: '总数增加',
                sourceBiz: '供应商手动维护',
                sourceBizOrderNo: null,
                stockDate: null,
              },
              {
                createTime: '2022-11-29 08:01:25',
                supplierWareHouseCode: '12055',
                supplierWareHouse: '',
                stockPartCode: null,
                stockPartName: null,
                sku: '2012920010104',
                skuName: 'TEST',
                ctrlWay: 3,
                ctrlNum: 10944,
                ctrlObj: '同步覆盖',
                sourceBiz: '同步供应商在单库存',
                sourceBizOrderNo: null,
                stockDate: null,
              },
            ],
            total: 614118,
            size: 10,
            current: 1,
            pages: 61412,
          },
        };

      this.tableData = res.data.records
    },
    handleSelectionChange(val) {
        console.log(val);
    }
  },
};
</script>
