<template>
    <div>
      <el-dialog title="添加sku" :visible.sync="visible" :before-close="close"
        top="25vh" :modal-append-to-body="false" :closeOnClickModal="false" width="450px">
        <div class="dialog_body">
          <el-form size="small" :model="form" :rules="rules" :inline="true" label-width="100px" label-position="top" ref="skuForm">
            <el-form-item prop="warehouse" label="供应商仓库">
                <el-select v-model="form.warehouse" clearable @change="warehouseChose">
                    <el-option v-for="warehouse in warehouseList" :key="warehouse.locationCode" :value="warehouse.locationCode" :label="warehouse.locationName">
                        <span>[{{warehouse.locationCode}}] </span>
                        <span>{{warehouse.locationName}}</span>
                    </el-option>
                </el-select>
            </el-form-item>
            <el-form-item prop="sku" label="SKU">
                <el-select v-model="form.sku" clearable :disabled="form.warehouse == ''">
                    <el-option v-for="sku in skuList" :key="sku.skuCode" :value="sku.skuCode" :label="sku.skuName">
                        <span>[{{sku.skuCode}}] </span>
                        <span>{{sku.skuName}}</span>
                    </el-option>
                </el-select>
            </el-form-item>
          </el-form>
          <div class="dialog_footer">
            <el-button type="" size="small" @click="close()">取消</el-button>
            <el-button type="primary" size="small" @click="submit()">创建</el-button>
          </div>
        </div>
      </el-dialog>
    </div>
  </template>
  
<script>

export default {
  name: "skuForm",
  components: {},
  props: {
    visible: {
      default: false,
    },
  },
  data() {
    return {
      form: {
          warehouse: "",
          sku: ""
      },
      rules: {
        warehouse: [
            { required: true, message: '请选择供应商仓库', trigger: 'change' }
        ],
        sku: [
            { required: true, message: '请选择SKU', trigger: 'change' }
        ],
      },
      warehouseList: [],
      skuList: []
    };
  },
  created() {
    this.getWarehouseList()
    this.getskuList()
  },
  methods: {
    close() {
      this.$emit("close");
    },
    getWarehouseList() {
        const res = {
            "code": 200,
            "msg": "success",
            "data": {
                "records": [
                    {
                        "tenant": null,
                        "departmentGroupCode": null,
                        "departmentGroupName": null,
                        "locationCode": "10000",
                        "locationName": "广州乐言文创实业有限公司",
                        "status": null,
                        "locationType": null,
                        "businessForm": null,
                        "contact": null,
                        "contactNum": null,
                        "regionCode": null,
                        "regionName": null,
                        "provinceCode": null,
                        "provinceName": null,
                        "cityCode": null,
                        "cityName": null,
                        "areaCode": null,
                        "areaName": null,
                        "address": null,
                        "postCode": null
                    },
                    {
                        "tenant": null,
                        "departmentGroupCode": null,
                        "departmentGroupName": null,
                        "locationCode": "10001",
                        "locationName": "福建集成伞业有限公司",
                        "status": null,
                        "locationType": null,
                        "businessForm": null,
                        "contact": null,
                        "contactNum": null,
                        "regionCode": null,
                        "regionName": null,
                        "provinceCode": null,
                        "provinceName": null,
                        "cityCode": null,
                        "cityName": null,
                        "areaCode": null,
                        "areaName": null,
                        "address": null,
                        "postCode": null
                    },
                    {
                        "tenant": null,
                        "departmentGroupCode": null,
                        "departmentGroupName": null,
                        "locationCode": "10002",
                        "locationName": "浙江新光饰品股份有限公司",
                        "status": null,
                        "locationType": null,
                        "businessForm": null,
                        "contact": null,
                        "contactNum": null,
                        "regionCode": null,
                        "regionName": null,
                        "provinceCode": null,
                        "provinceName": null,
                        "cityCode": null,
                        "cityName": null,
                        "areaCode": null,
                        "areaName": null,
                        "address": null,
                        "postCode": null
                    },
                    {
                        "tenant": null,
                        "departmentGroupCode": null,
                        "departmentGroupName": null,
                        "locationCode": "10006",
                        "locationName": "广州市玛莉安化妆用品有限公司",
                        "status": null,
                        "locationType": null,
                        "businessForm": null,
                        "contact": null,
                        "contactNum": null,
                        "regionCode": null,
                        "regionName": null,
                        "provinceCode": null,
                        "provinceName": null,
                        "cityCode": null,
                        "cityName": null,
                        "areaCode": null,
                        "areaName": null,
                        "address": null,
                        "postCode": null
                    },
                    {
                        "tenant": null,
                        "departmentGroupCode": null,
                        "departmentGroupName": null,
                        "locationCode": "10010",
                        "locationName": "清远市伟诚塑料制品有限公司",
                        "status": null,
                        "locationType": null,
                        "businessForm": null,
                        "contact": null,
                        "contactNum": null,
                        "regionCode": null,
                        "regionName": null,
                        "provinceCode": null,
                        "provinceName": null,
                        "cityCode": null,
                        "cityName": null,
                        "areaCode": null,
                        "areaName": null,
                        "address": null,
                        "postCode": null
                    },
                    {
                        "tenant": null,
                        "departmentGroupCode": null,
                        "departmentGroupName": null,
                        "locationCode": "10015",
                        "locationName": "广东海兴塑胶有限公司",
                        "status": null,
                        "locationType": null,
                        "businessForm": null,
                        "contact": null,
                        "contactNum": null,
                        "regionCode": null,
                        "regionName": null,
                        "provinceCode": null,
                        "provinceName": null,
                        "cityCode": null,
                        "cityName": null,
                        "areaCode": null,
                        "areaName": null,
                        "address": null,
                        "postCode": null
                    },
                    {
                        "tenant": null,
                        "departmentGroupCode": null,
                        "departmentGroupName": null,
                        "locationCode": "10025",
                        "locationName": "东莞市莞美饰品有限公司",
                        "status": null,
                        "locationType": null,
                        "businessForm": null,
                        "contact": null,
                        "contactNum": null,
                        "regionCode": null,
                        "regionName": null,
                        "provinceCode": null,
                        "provinceName": null,
                        "cityCode": null,
                        "cityName": null,
                        "areaCode": null,
                        "areaName": null,
                        "address": null,
                        "postCode": null
                    },
                    {
                        "tenant": null,
                        "departmentGroupCode": null,
                        "departmentGroupName": null,
                        "locationCode": "10032",
                        "locationName": "黄岩坚美塑胶有限公司",
                        "status": null,
                        "locationType": null,
                        "businessForm": null,
                        "contact": null,
                        "contactNum": null,
                        "regionCode": null,
                        "regionName": null,
                        "provinceCode": null,
                        "provinceName": null,
                        "cityCode": null,
                        "cityName": null,
                        "areaCode": null,
                        "areaName": null,
                        "address": null,
                        "postCode": null
                    },
                    {
                        "tenant": null,
                        "departmentGroupCode": null,
                        "departmentGroupName": null,
                        "locationCode": "10034",
                        "locationName": "中山市紫丁香实业有限公司",
                        "status": null,
                        "locationType": null,
                        "businessForm": null,
                        "contact": null,
                        "contactNum": null,
                        "regionCode": null,
                        "regionName": null,
                        "provinceCode": null,
                        "provinceName": null,
                        "cityCode": null,
                        "cityName": null,
                        "areaCode": null,
                        "areaName": null,
                        "address": null,
                        "postCode": null
                    },
                    {
                        "tenant": null,
                        "departmentGroupCode": null,
                        "departmentGroupName": null,
                        "locationCode": "10054",
                        "locationName": "义乌市英俊日用制品有限公司",
                        "status": null,
                        "locationType": null,
                        "businessForm": null,
                        "contact": null,
                        "contactNum": null,
                        "regionCode": null,
                        "regionName": null,
                        "provinceCode": null,
                        "provinceName": null,
                        "cityCode": null,
                        "cityName": null,
                        "areaCode": null,
                        "areaName": null,
                        "address": null,
                        "postCode": null
                    },
                    {
                        "tenant": null,
                        "departmentGroupCode": null,
                        "departmentGroupName": null,
                        "locationCode": "10071",
                        "locationName": "宁波瑞孚工业集团有限公司",
                        "status": null,
                        "locationType": null,
                        "businessForm": null,
                        "contact": null,
                        "contactNum": null,
                        "regionCode": null,
                        "regionName": null,
                        "provinceCode": null,
                        "provinceName": null,
                        "cityCode": null,
                        "cityName": null,
                        "areaCode": null,
                        "areaName": null,
                        "address": null,
                        "postCode": null
                    },
                    {
                        "tenant": null,
                        "departmentGroupCode": null,
                        "departmentGroupName": null,
                        "locationCode": "10072",
                        "locationName": "义乌市百丽饰品厂",
                        "status": null,
                        "locationType": null,
                        "businessForm": null,
                        "contact": null,
                        "contactNum": null,
                        "regionCode": null,
                        "regionName": null,
                        "provinceCode": null,
                        "provinceName": null,
                        "cityCode": null,
                        "cityName": null,
                        "areaCode": null,
                        "areaName": null,
                        "address": null,
                        "postCode": null
                    },
                    {
                        "tenant": null,
                        "departmentGroupCode": null,
                        "departmentGroupName": null,
                        "locationCode": "10100",
                        "locationName": "温州智博印业有限公司",
                        "status": null,
                        "locationType": null,
                        "businessForm": null,
                        "contact": null,
                        "contactNum": null,
                        "regionCode": null,
                        "regionName": null,
                        "provinceCode": null,
                        "provinceName": null,
                        "cityCode": null,
                        "cityName": null,
                        "areaCode": null,
                        "areaName": null,
                        "address": null,
                        "postCode": null
                    },
                    {
                        "tenant": null,
                        "departmentGroupCode": null,
                        "departmentGroupName": null,
                        "locationCode": "10104",
                        "locationName": "汕头市怡佳塑胶制品有限公司",
                        "status": null,
                        "locationType": null,
                        "businessForm": null,
                        "contact": null,
                        "contactNum": null,
                        "regionCode": null,
                        "regionName": null,
                        "provinceCode": null,
                        "provinceName": null,
                        "cityCode": null,
                        "cityName": null,
                        "areaCode": null,
                        "areaName": null,
                        "address": null,
                        "postCode": null
                    },
                    {
                        "tenant": null,
                        "departmentGroupCode": null,
                        "departmentGroupName": null,
                        "locationCode": "10116",
                        "locationName": "珠海市合顺兴日化股份有限公司",
                        "status": null,
                        "locationType": null,
                        "businessForm": null,
                        "contact": null,
                        "contactNum": null,
                        "regionCode": null,
                        "regionName": null,
                        "provinceCode": null,
                        "provinceName": null,
                        "cityCode": null,
                        "cityName": null,
                        "areaCode": null,
                        "areaName": null,
                        "address": null,
                        "postCode": null
                    },
                    {
                        "tenant": null,
                        "departmentGroupCode": null,
                        "departmentGroupName": null,
                        "locationCode": "10117",
                        "locationName": "新丰香知韵工艺品有限公司",
                        "status": null,
                        "locationType": null,
                        "businessForm": null,
                        "contact": null,
                        "contactNum": null,
                        "regionCode": null,
                        "regionName": null,
                        "provinceCode": null,
                        "provinceName": null,
                        "cityCode": null,
                        "cityName": null,
                        "areaCode": null,
                        "areaName": null,
                        "address": null,
                        "postCode": null
                    },
                    {
                        "tenant": null,
                        "departmentGroupCode": null,
                        "departmentGroupName": null,
                        "locationCode": "10132",
                        "locationName": "青岛澳捷尔文化产业有限公司",
                        "status": null,
                        "locationType": null,
                        "businessForm": null,
                        "contact": null,
                        "contactNum": null,
                        "regionCode": null,
                        "regionName": null,
                        "provinceCode": null,
                        "provinceName": null,
                        "cityCode": null,
                        "cityName": null,
                        "areaCode": null,
                        "areaName": null,
                        "address": null,
                        "postCode": null
                    },
                    {
                        "tenant": null,
                        "departmentGroupCode": null,
                        "departmentGroupName": null,
                        "locationCode": "10165",
                        "locationName": "东莞市钟鑫塑料日用品有限公司",
                        "status": null,
                        "locationType": null,
                        "businessForm": null,
                        "contact": null,
                        "contactNum": null,
                        "regionCode": null,
                        "regionName": null,
                        "provinceCode": null,
                        "provinceName": null,
                        "cityCode": null,
                        "cityName": null,
                        "areaCode": null,
                        "areaName": null,
                        "address": null,
                        "postCode": null
                    },
                    {
                        "tenant": null,
                        "departmentGroupCode": null,
                        "departmentGroupName": null,
                        "locationCode": "10166",
                        "locationName": "深圳市三德大康电子有限公司",
                        "status": null,
                        "locationType": null,
                        "businessForm": null,
                        "contact": null,
                        "contactNum": null,
                        "regionCode": null,
                        "regionName": null,
                        "provinceCode": null,
                        "provinceName": null,
                        "cityCode": null,
                        "cityName": null,
                        "areaCode": null,
                        "areaName": null,
                        "address": null,
                        "postCode": null
                    },
                    {
                        "tenant": null,
                        "departmentGroupCode": null,
                        "departmentGroupName": null,
                        "locationCode": "10176",
                        "locationName": "深圳市乐迈科技有限公司",
                        "status": null,
                        "locationType": null,
                        "businessForm": null,
                        "contact": null,
                        "contactNum": null,
                        "regionCode": null,
                        "regionName": null,
                        "provinceCode": null,
                        "provinceName": null,
                        "cityCode": null,
                        "cityName": null,
                        "areaCode": null,
                        "areaName": null,
                        "address": null,
                        "postCode": null
                    }
                ],
                "total": 108,
                "size": 20,
                "current": 1,
                "pages": 6
            },
            "success": true
        }
        this.warehouseList = res.data.records
    },
    getskuList() {
        const res = {
            "code": 200,
            "msg": "success",
            "data": [
                {
                    "skuCode": "0000000011",
                    "skuType": "Z004",
                    "barCode": "0000000000017",
                    "skuName": "TEST",
                    "tinyCategoryCode": "10010101",
                    "tinyCategoryName": null,
                    "copyrightCode": "",
                    "seriesCode": "",
                    "bigCategoryCode": "35",
                    "bigCategoryName": null,
                    "middleCategoryCode": "3500",
                    "middleCategoryName": null,
                    "smallCategoryCode": "350001",
                    "smallCategoryName": null,
                    "displayCategoryCode": "",
                    "combinePrice": 1000,
                    "launchVersionCode": "",
                    "status": "2"
                },
                {
                    "skuCode": "0000000012",
                    "skuType": "Z004",
                    "barCode": "0000000000024",
                    "skuName": "TEST",
                    "tinyCategoryCode": "10010101",
                    "tinyCategoryName": null,
                    "copyrightCode": "",
                    "seriesCode": "",
                    "bigCategoryCode": "35",
                    "bigCategoryName": null,
                    "middleCategoryCode": "3500",
                    "middleCategoryName": null,
                    "smallCategoryCode": "350001",
                    "smallCategoryName": null,
                    "displayCategoryCode": "",
                    "combinePrice": 1000,
                    "launchVersionCode": "",
                    "status": "2"
                },
                {
                    "skuCode": "0000000013",
                    "skuType": "Z004",
                    "barCode": "0000000000130",
                    "skuName": "TEST",
                    "tinyCategoryCode": "10010101",
                    "tinyCategoryName": null,
                    "copyrightCode": "",
                    "seriesCode": "",
                    "bigCategoryCode": "35",
                    "bigCategoryName": null,
                    "middleCategoryCode": "3500",
                    "middleCategoryName": null,
                    "smallCategoryCode": "350001",
                    "smallCategoryName": null,
                    "displayCategoryCode": "",
                    "combinePrice": 1500,
                    "launchVersionCode": "",
                    "status": "2"
                },
                {
                    "skuCode": "0000000014",
                    "skuType": "Z004",
                    "barCode": "0000000000147",
                    "skuName": "TEST",
                    "tinyCategoryCode": "10010101",
                    "tinyCategoryName": null,
                    "copyrightCode": "",
                    "seriesCode": "",
                    "bigCategoryCode": "35",
                    "bigCategoryName": null,
                    "middleCategoryCode": "3500",
                    "middleCategoryName": null,
                    "smallCategoryCode": "350001",
                    "smallCategoryName": null,
                    "displayCategoryCode": "",
                    "combinePrice": 2000,
                    "launchVersionCode": "",
                    "status": "2"
                },
                {
                    "skuCode": "0000000018",
                    "skuType": "Z004",
                    "barCode": "0000000000185",
                    "skuName": "TEST",
                    "tinyCategoryCode": "10010101",
                    "tinyCategoryName": null,
                    "copyrightCode": "",
                    "seriesCode": "",
                    "bigCategoryCode": "35",
                    "bigCategoryName": null,
                    "middleCategoryCode": "3500",
                    "middleCategoryName": null,
                    "smallCategoryCode": "350001",
                    "smallCategoryName": null,
                    "displayCategoryCode": "",
                    "combinePrice": 3900,
                    "launchVersionCode": "",
                    "status": "2"
                },
                {
                    "skuCode": "0000000020",
                    "skuType": "Z004",
                    "barCode": "0000000000208",
                    "skuName": "TEST",
                    "tinyCategoryCode": "10010101",
                    "tinyCategoryName": null,
                    "copyrightCode": "",
                    "seriesCode": "",
                    "bigCategoryCode": "35",
                    "bigCategoryName": null,
                    "middleCategoryCode": "3500",
                    "middleCategoryName": null,
                    "smallCategoryCode": "350001",
                    "smallCategoryName": null,
                    "displayCategoryCode": "",
                    "combinePrice": 4900,
                    "launchVersionCode": "",
                    "status": "2"
                },
                {
                    "skuCode": "0100000011",
                    "skuType": "Z001",
                    "barCode": "4500901000117/4502337000112/4506597000110",
                    "skuName": "TEST",
                    "tinyCategoryCode": "10030102",
                    "tinyCategoryName": null,
                    "copyrightCode": "",
                    "seriesCode": "",
                    "bigCategoryCode": "29",
                    "bigCategoryName": null,
                    "middleCategoryCode": "2901",
                    "middleCategoryName": null,
                    "smallCategoryCode": "290130",
                    "smallCategoryName": null,
                    "displayCategoryCode": "2219",
                    "combinePrice": 1000,
                    "launchVersionCode": "",
                    "status": "2"
                },
                {
                    "skuCode": "0100000021",
                    "skuType": "Z001",
                    "barCode": "4500901000216",
                    "skuName": "TEST",
                    "tinyCategoryCode": "10030102",
                    "tinyCategoryName": null,
                    "copyrightCode": "",
                    "seriesCode": "",
                    "bigCategoryCode": "29",
                    "bigCategoryName": null,
                    "middleCategoryCode": "2901",
                    "middleCategoryName": null,
                    "smallCategoryCode": "290130",
                    "smallCategoryName": null,
                    "displayCategoryCode": "2219",
                    "combinePrice": 1000,
                    "launchVersionCode": "",
                    "status": "2"
                },
                {
                    "skuCode": "0100000031",
                    "skuType": "Z001",
                    "barCode": "4500901000315/4502337000310/4506597000318",
                    "skuName": "TEST",
                    "tinyCategoryCode": "10030102",
                    "tinyCategoryName": null,
                    "copyrightCode": "",
                    "seriesCode": "",
                    "bigCategoryCode": "29",
                    "bigCategoryName": null,
                    "middleCategoryCode": "2901",
                    "middleCategoryName": null,
                    "smallCategoryCode": "290130",
                    "smallCategoryName": null,
                    "displayCategoryCode": "2219",
                    "combinePrice": 1000,
                    "launchVersionCode": "",
                    "status": "2"
                },
                {
                    "skuCode": "0100000041",
                    "skuType": "Z001",
                    "barCode": "4500901000414",
                    "skuName": "TEST",
                    "tinyCategoryCode": "10030102",
                    "tinyCategoryName": null,
                    "copyrightCode": "",
                    "seriesCode": "",
                    "bigCategoryCode": "29",
                    "bigCategoryName": null,
                    "middleCategoryCode": "2901",
                    "middleCategoryName": null,
                    "smallCategoryCode": "290130",
                    "smallCategoryName": null,
                    "displayCategoryCode": "2219",
                    "combinePrice": 1000,
                    "launchVersionCode": "",
                    "status": "2"
                },
                {
                    "skuCode": "0100000051",
                    "skuType": "Z001",
                    "barCode": "4500901000513",
                    "skuName": "TEST",
                    "tinyCategoryCode": "10030102",
                    "tinyCategoryName": null,
                    "copyrightCode": "",
                    "seriesCode": "",
                    "bigCategoryCode": "29",
                    "bigCategoryName": null,
                    "middleCategoryCode": "2901",
                    "middleCategoryName": null,
                    "smallCategoryCode": "290130",
                    "smallCategoryName": null,
                    "displayCategoryCode": "2219",
                    "combinePrice": 1000,
                    "launchVersionCode": "",
                    "status": "2"
                },
                {
                    "skuCode": "0100000061",
                    "skuType": "Z001",
                    "barCode": "4501901000619",
                    "skuName": "TEST",
                    "tinyCategoryCode": "10010102",
                    "tinyCategoryName": null,
                    "copyrightCode": "",
                    "seriesCode": "",
                    "bigCategoryCode": "20",
                    "bigCategoryName": null,
                    "middleCategoryCode": "2001",
                    "middleCategoryName": null,
                    "smallCategoryCode": "200152",
                    "smallCategoryName": null,
                    "displayCategoryCode": "2170",
                    "combinePrice": 1000,
                    "launchVersionCode": "",
                    "status": "2"
                },
                {
                    "skuCode": "0100000071",
                    "skuType": "Z001",
                    "barCode": "4501901000718",
                    "skuName": "TEST",
                    "tinyCategoryCode": "10010102",
                    "tinyCategoryName": null,
                    "copyrightCode": "",
                    "seriesCode": "",
                    "bigCategoryCode": "20",
                    "bigCategoryName": null,
                    "middleCategoryCode": "2001",
                    "middleCategoryName": null,
                    "smallCategoryCode": "200152",
                    "smallCategoryName": null,
                    "displayCategoryCode": "2170",
                    "combinePrice": 1000,
                    "launchVersionCode": "",
                    "status": "2"
                },
                {
                    "skuCode": "0100000081",
                    "skuType": "Z001",
                    "barCode": "4501901000817",
                    "skuName": "TEST",
                    "tinyCategoryCode": "10010102",
                    "tinyCategoryName": null,
                    "copyrightCode": "",
                    "seriesCode": "",
                    "bigCategoryCode": "20",
                    "bigCategoryName": null,
                    "middleCategoryCode": "2001",
                    "middleCategoryName": null,
                    "smallCategoryCode": "200152",
                    "smallCategoryName": null,
                    "displayCategoryCode": "2170",
                    "combinePrice": 1000,
                    "launchVersionCode": "",
                    "status": "2"
                },
                {
                    "skuCode": "0100000091",
                    "skuType": "Z001",
                    "barCode": "4501901000916",
                    "skuName": "TEST",
                    "tinyCategoryCode": "10010102",
                    "tinyCategoryName": null,
                    "copyrightCode": "",
                    "seriesCode": "",
                    "bigCategoryCode": "20",
                    "bigCategoryName": null,
                    "middleCategoryCode": "2001",
                    "middleCategoryName": null,
                    "smallCategoryCode": "200152",
                    "smallCategoryName": null,
                    "displayCategoryCode": "2170",
                    "combinePrice": 1000,
                    "launchVersionCode": "",
                    "status": "2"
                },
                {
                    "skuCode": "0100000101",
                    "skuType": "Z001",
                    "barCode": "4501901001012",
                    "skuName": "TEST",
                    "tinyCategoryCode": "10010102",
                    "tinyCategoryName": null,
                    "copyrightCode": "",
                    "seriesCode": "",
                    "bigCategoryCode": "20",
                    "bigCategoryName": null,
                    "middleCategoryCode": "2001",
                    "middleCategoryName": null,
                    "smallCategoryCode": "200152",
                    "smallCategoryName": null,
                    "displayCategoryCode": "2170",
                    "combinePrice": 1000,
                    "launchVersionCode": "",
                    "status": "2"
                },
                {
                    "skuCode": "0100000111",
                    "skuType": "Z001",
                    "barCode": "4501901001111",
                    "skuName": "TEST",
                    "tinyCategoryCode": "10010102",
                    "tinyCategoryName": null,
                    "copyrightCode": "",
                    "seriesCode": "",
                    "bigCategoryCode": "20",
                    "bigCategoryName": null,
                    "middleCategoryCode": "2001",
                    "middleCategoryName": null,
                    "smallCategoryCode": "200152",
                    "smallCategoryName": null,
                    "displayCategoryCode": "2170",
                    "combinePrice": 1000,
                    "launchVersionCode": "",
                    "status": "2"
                },
                {
                    "skuCode": "0100000121",
                    "skuType": "Z001",
                    "barCode": "4501901001210",
                    "skuName": "TEST",
                    "tinyCategoryCode": "10010102",
                    "tinyCategoryName": null,
                    "copyrightCode": "",
                    "seriesCode": "",
                    "bigCategoryCode": "20",
                    "bigCategoryName": null,
                    "middleCategoryCode": "2001",
                    "middleCategoryName": null,
                    "smallCategoryCode": "200152",
                    "smallCategoryName": null,
                    "displayCategoryCode": "2170",
                    "combinePrice": 1000,
                    "launchVersionCode": "",
                    "status": "2"
                },
                {
                    "skuCode": "0100000131",
                    "skuType": "Z001",
                    "barCode": "4501901001319",
                    "skuName": "TEST",
                    "tinyCategoryCode": "10010102",
                    "tinyCategoryName": null,
                    "copyrightCode": "",
                    "seriesCode": "",
                    "bigCategoryCode": "20",
                    "bigCategoryName": null,
                    "middleCategoryCode": "2001",
                    "middleCategoryName": null,
                    "smallCategoryCode": "200152",
                    "smallCategoryName": null,
                    "displayCategoryCode": "2170",
                    "combinePrice": 1000,
                    "launchVersionCode": "",
                    "status": "2"
                },
                {
                    "skuCode": "0100000141",
                    "skuType": "Z001",
                    "barCode": "4501901001418",
                    "skuName": "TEST",
                    "tinyCategoryCode": "10010102",
                    "tinyCategoryName": null,
                    "copyrightCode": "",
                    "seriesCode": "",
                    "bigCategoryCode": "20",
                    "bigCategoryName": null,
                    "middleCategoryCode": "2001",
                    "middleCategoryName": null,
                    "smallCategoryCode": "200152",
                    "smallCategoryName": null,
                    "displayCategoryCode": "2170",
                    "combinePrice": 1000,
                    "launchVersionCode": "",
                    "status": "2"
                }
            ],
            "success": true
        }

        this.skuList = res.data
    },
    warehouseChose() {
        this.form.sku = ""
    },
    submit() {
        this.$refs['skuForm'].validate((valid) => {
          if (valid) {
            this.$message.success('新建成功')
            this.close()
          } else {
            console.log('error submit!!');
            return false;
          }
        });
    }
  },
};
</script>
<style lang="scss" src="@/assets/styles/element/input.scss"  scoped>
  
  </style>
  